# Generated by Django 4.1.3 on 2022-12-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_alter_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('ML', 'Milk'), ('GH', 'Ghee'), ('CR', 'Curd'), ('LS', 'Lassi'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
