# Generated by Django 4.1.3 on 2022-12-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_rename_subject_contact_title_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('CR', 'Curd'), ('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CZ', 'Cheese')], max_length=2),
        ),
    ]
