# Generated by Django 4.1.3 on 2022-12-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('CR', 'Curd'), ('CZ', 'Cheese'), ('PN', 'Paneer'), ('ML', 'Milk'), ('LS', 'Lassi')], max_length=2),
        ),
    ]
